language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: udt1WJ6PU4tKj0BRewFWMEzE0GTsb+Djngh2pUivky3GWliP3j7ZegDGLPFiLLLh0nKtfmjASHNx0Lmu8abgtGG7G5pUpWhWSfzqyGWCYB5sdHMsBzJCgRW/WEDdRucu6LWz/kb8x5a/Bx6bnbM+GQHY9M4TTtnDa012Z2VfBzalS3xWD8bdJOV2i37WXqsKnYnsbFhpyIZDSR/u/3KSI1r23aoG+T1ZoqezxFONRW5GWu6VgWSvmgTkMDQasen5ucuA+z11VEwNDN9Zg0tzZMJapg9f6OLISUBSK6eokPdh05+Wf2mnvsQK7AnDhsiXK5QfOSGkQEFoo/3V6AP7tJmvh3kpnChNPSR+lL5p5GCFYb40bnLAeEe5ZQkezEfaHutFF1tuOrvC+rSXTUd2mmhbz1QZquUY5+BftGpBxVokU8HyJxclY2XUrduUbw+XAUACGmLhv0tstWzA5Y+rkRdS90/o0WIbNChpgVZFR/IuNOc2IH99ZmWVH0o4pt+IHA3whLUEh0P3nz42j4Z/NNJdnX0FMBbsyN8G2oPEPu5px7B4PtaKdNTkoXj5zJRr2fDVY7b1zwgT9vtMEDdeP2GsHJ5sjhtLqu4v15JjcMiyPKPlr47zyHfBi2uvOlIaxnnq2t0g4nhzgE3e4pxcAdfCfFUcS73C8WsXOL/Eqc8=
  app: travel-journal-app
  on:
    repo: annasheik/travel-journal
